### ISSUE TITLE
mkdirp dependency is missing in the package.json

### ISSUE THREAD

**Issue by davazp** [viankakrisna/loader-fs-cache#1]
I think this also breaks eslint-loader

**Comment by kerrmarin** [comment]
This should now be fixed by https://github.com/viankakrisna/loader-fs-cache/pull/2

**Comment by viankakrisna** [comment]
Yep, released it as 1.0.1. Thanks for the issue and PR! Feel free to report and pr if you found more bugs/improvement :)
