### ISSUE TITLE
mkdirp dependency on minimist has security vulnerability 

### ISSUE THREAD

**Issue by okoshy** [viankakrisna/loader-fs-cache#5]
https://www.npmjs.com/advisories/1179 
https://github.com/isaacs/node-mkdirp/issues/7

**Comment by webmaster128** [comment]
There is mkdirp version 0.5.3 to the rescue. You just need to change `0.5.1` to `^0.5.1` to help users of this package.

**Comment by neokeld** [comment]
I've publish a fork here : https://www.npmjs.com/package/create-fs-cache
I hope it will be useless.
If it is needed i will maintain it.
